version: "3"

logs:
  level: info

rpc:
  listen: tcp://127.0.0.1:6001

server:
  command: "php app/index.php"
  env:
    - MODE: "production"

http:
  address: 0.0.0.0:5173
  pool:
    num_workers: 0
